"""empty message

Revision ID: e32ebb09f016
Revises: 
Create Date: 2023-10-03 21:36:39.444648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32ebb09f016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))

    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('label')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
